### ISSUE TITLE
Newcord Outline

### ISSUE THREAD

**Issue by Brownie-cell** [Kaiidoo/Newcord#2]
Hey kaiidoo! I love the newcord style, but the only reason i dont use it is because of the outline. Is there any way you can make a different version without the outline or is there a customization option for it? Thank you!

PS: I'm talking about this outline.
![image](https://user-images.githubusercontent.com/62781684/135356819-4f6e840a-900f-41ec-ba2e-aaf371b8d2e1.png)

**Comment by MaximeDawn** [comment]
I guess there will be a customisation later, for now, simply put this at the end of the file : 

`:root {
    --window-padding: 0px;
}`

**Comment by Brownie-cell** [comment]
thank you so much i just fixed it :))

**Comment by Kaiidoo** [comment]
Actually, there is already a customisation for this,
and by the way I'm sorry I don't find the time to do the cusomisation guide and to work on the theme TvT
anyway

1. Edit the theme by cliking on the edit button.
![image](https://user-images.githubusercontent.com/77465726/135400930-90d54388-2154-4db6-957b-7bc209461fa2.png)

2. Enlarge the window that has just opened by cliking on the button at the left of the close button.
![image](https://user-images.githubusercontent.com/77465726/135401641-1ed695a4-3661-4c02-ab21-b367a375deeb.png)

3. As write below, add "/*" before the "@ import" of the stuff that you don't want to use.
![image](https://user-images.githubusercontent.com/77465726/135403057-a29c6886-3a68-4e4b-92a7-a646647e4791.png)

4. For the outline it should look like this.
![image](https://user-images.githubusercontent.com/77465726/135403560-27559f15-cd7b-403e-9283-db4a52a767f9.png)

5. Don't forget to save by cliking on the button below "Newcord".
![image](https://user-images.githubusercontent.com/77465726/135404184-ee21cb96-8bfe-4eda-b8cd-6e1062216198.png)

And there you are!
![image](https://user-images.githubusercontent.com/77465726/135404664-6bb37253-8a72-461f-9cbe-3d79560ba379.png)
