### ISSUE TITLE
Unable to use plugins

### ISSUE THREAD

**Issue by abinroy04** [Kaiidoo/Newcord#3]
![image](https://user-images.githubusercontent.com/85763004/137743962-80a0dda4-6e9d-4e68-89ff-f3fb2fb19f92.png)

There is a plugin that allows you to send emojis as links named "DiscordFreeEmojis".
Usually I am just able to click on the emojis and it will get sent, but with the theme, I am unable to click on them.

**Comment by Kaiidoo** [comment]
OMG hii, sorry for the very, very late response ..........
Sooo, I don't know if you found the solution, but I think you were using [this plugin](https://betterdiscord.app/plugin/FreeEmojis) by BetterDiscord, and unfortunately it doesn't work any more even if you disable Newcord.
It's why, if you want to use a plugin that allows you to send emojis as links, I recommend you to use [this one](https://betterdiscord.app/plugin/Freemoji) which also works with Newcord ! :D
