### ISSUE TITLE
How to remove the border?

### ISSUE THREAD

**Issue by FahadSec** [Kaiidoo/Newcord#4]
<img width="142" alt="image" src="https://user-images.githubusercontent.com/75849983/142776244-0d4809ef-bfe5-4f76-9e66-5ca5200fbca2.png">

**Comment by FahadSec** [comment]
Nevermind! I just commented the line after`/* To center the Discord window and add it an outline */`

**Comment by Kaiidoo** [comment]
Oh- I was not aware of this bug on Mac! o-o sorry.
