### ISSUE TITLE
Can't not close notification

### ISSUE THREAD

**Issue by duongtuan303030** [Kaiidoo/Newcord#5]
# If click close notification it close discord windows
![image](https://user-images.githubusercontent.com/80153297/142842458-78b7c2de-c637-4bef-b6a8-41de07f3a9dc.png)

**Comment by MaximeDawn** [comment]
I'm having the same issue with the "InAppNotifications" plugin :/ The thing i do is disable the theme, then re-enable it.

**Comment by Kaiidoo** [comment]
Oh- sorry for this bug ... ╭( ･ㅂ･)و ̑̑
I fixed it.
You can now enjoy doing streams without this ribbon (˶• ֊ •˶)

**Comment by Kaiidoo** [comment]
> 

You talk about [this plugin](https://betterdiscord.app/plugin/AppNotifications) ?

**Comment by MaximeDawn** [comment]
> 

Nope, [this one](https://1lighty.github.io/BetterDiscordStuff/?plugin=InAppNotifications)

**Comment by Kaiidoo** [comment]
> > 
> 
> Nope, [this one](https://1lighty.github.io/BetterDiscordStuff/?plugin=InAppNotifications)

It's fixed. Enjoy ! ʚ₍ᐢ › ༝ ‹ ᐢ₎ɞ
